name: "\U0001F680 Feature request"
description: Suggest an idea for the Israel Hiking Map project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to improve the Israel Hiking Map.
        Please fill in as much of the following form as you're able.
  - type: textarea
    attributes:
      label: Problem Statement
      description: |
        What is the problem you are facing? Please describe it in detail.
      placeholder: |
        If you have a screenshots, please attach them.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the way to solve the problem. If you already have something in mind... PRs are welcome!
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered or tried?
      description: |
        Describe the other ways you have considered or tried to solve the problem, if any.
        Please let us know how each of them failed to solve it.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Things I think the developers should know, images, links etc.
