name: "\U00002753 Question"
description: Ask a question about the Israel Hiking Map project
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contacting the Israel Hiking Map.
        
        Please checkout the [Frequently Asked Questions](https://github.com/IsraelHikingMap/Site/wiki/Israel-Hiking-Maps-FAQ) and the video clips there.

        You may also consider asking on [OUR Facebook group](https://www.facebook.com/groups/israelhikingmap) 

        Otherwise, please [open a new discussion](https://github.com/IsraelHikingMap/Site/discussions/new).
