// Generates the ui icon font and its css from svg folders.
// Add or replace an svg in one of the folders below, run this script, commit the result.
//
// The folders are the definition of what the font contains - every svg becomes a glyph named after
// its file. font-SVGs holds icons that only exist for the ui, the sprite folder is shared with the
// map, and the artwork listed in spriteOnlyArtwork is skipped since it is never a ui icon.
// Folders are in priority order, so if the same name appears twice the first folder wins.
import { SVGIcons2SVGFontStream } from 'svgicons2svgfont';
import svg2ttf from 'svg2ttf';
import { compress } from 'wawoff2';
import fs from 'fs';
import path from 'path';
import { Readable } from 'stream';

const svgFolders = [
    './scripts/font-SVGs',
    './scripts/SVGs'
];
/** Map artwork that is never a ui icon, regardless of what the file happens to be called. */
const spriteOnlyArtwork = [/pattern/, /^arrowline$/, /^arrowhead$/, /^triangle$/, /^dot$/];
/**
 * Icon classes that are drawn by an svg filed under a different name. The map keeps both names
 * working - class names appear in saved user data, so they cannot simply be renamed - while the
 * artwork lives in exactly one place.
 */
const aliases: Record<string, string> = {
    archaeological: 'jar',
    bed: 'hotel',
    campsite: 'camping',
    circle: 'dot',
    flowers: 'flower',
    gate: 'gate-open',
    memorial: 'monument',
    waterhole: 'water-hole'
};
const fontName = 'mapeak';
const outputFont = `./src/fonts/${fontName}.woff2`;
const outputCss = './src/fonts/icons.css';
/** Private use area. Codepoints are an implementation detail - the css maps names to them. */
const firstCodepoint = 0xe900;

/** Every svg in every folder, keyed by icon name, first folder wins. */
function collectAllSvgs(): Map<string, string> {
    const all = new Map<string, string>();
    for (const folder of svgFolders) {
        for (const file of fs.readdirSync(folder).filter(f => f.endsWith('.svg')).sort()) {
            // The sprite folder uses underscores, the css classes use dashes.
            const name = path.basename(file, '.svg').replace(/_/g, '-');
            if (!all.has(name)) {
                all.set(name, path.join(folder, file));
            }
        }
    }
    return all;
}

function collectIcons(): Map<string, string> {
    const allSvgs = collectAllSvgs();
    const icons = new Map<string, string>();
    for (const [name, file] of allSvgs) {
        if (!spriteOnlyArtwork.some(rule => rule.test(name))) {
            icons.set(name, file);
        }
    }
    // Aliases borrow another icon's artwork, so the target may well be map artwork that is skipped
    // above and has no glyph of its own.
    for (const [name, target] of Object.entries(aliases)) {
        icons.set(name, allSvgs.get(target));
    }
    return icons;
}

/**
 * A font glyph has no colour of its own, it is painted with the surrounding text colour. Sprite
 * icons do carry fills - white ones would come out invisible - so they are stripped on the way in.
 */
function readMonochromeSvg(file: string): string {
    return fs.readFileSync(file, 'utf8')
        .replace(/\s(fill|stroke)="(?!none)[^"]*"/g, '')
        .replace(/(fill|stroke)\s*:\s*(?!none)[^;"]*;?/g, '');
}

function buildSvgFont(icons: Map<string, string>, codepoints: Map<string, number>): Promise<string> {
    return new Promise((resolve, reject) => {
        const stream = new SVGIcons2SVGFontStream({
            fontName,
            normalize: true,
            centerVertically: true,
            fontHeight: 1000
        });
        let svgFont = '';
        stream.on('data', (chunk: Buffer) => svgFont += chunk.toString());
        stream.on('end', () => resolve(svgFont));
        stream.on('error', reject);
        for (const [name, file] of icons) {
            const glyph = Readable.from([readMonochromeSvg(file)]) as Readable & { metadata?: unknown };
            glyph.metadata = { unicode: [String.fromCodePoint(codepoints.get(name))], name };
            stream.write(glyph);
        }
        stream.end();
    });
}

function buildCss(codepoints: Map<string, number>): string {
    const header =
`/* Generated by scripts/generate-icon-font.ts - do not edit by hand. */
@font-face {
  font-family: '${fontName}';
  src: url('${fontName}.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

[class^="icon-"], [class*=" icon-"] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: '${fontName}' !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`;
    const rules = [...codepoints.entries()]
        .map(([name, codepoint]) => `\n.icon-${name}:before {\n  content: "\\${codepoint.toString(16)}";\n}\n`);
    return header + rules.join('');
}

const icons = collectIcons();
// Sorting by name keeps codepoints stable so regenerating produces a readable diff.
const codepoints = new Map([...icons.keys()].sort().map((name, index) => [name, firstCodepoint + index] as const));

const svgFont = await buildSvgFont(icons, codepoints);
// A fixed timestamp keeps the output byte for byte identical when nothing changed.
const ttf = Buffer.from(svg2ttf(svgFont, { description: 'Mapeak icons', url: 'https://mapeak.com', ts: 0 }).buffer);
fs.writeFileSync(outputFont, await compress(ttf));
fs.writeFileSync(outputCss, buildCss(codepoints));

console.log(`Wrote ${outputFont} (${(fs.statSync(outputFont).size / 1024).toFixed(1)}kb) with ${icons.size} icons`);
console.log(`Wrote ${outputCss}`);
