import { components } from "./user-data.g.d.ts";

export type LatLngAltTime = components["schemas"]["LatLngAltTime"];
export type LayerData = components["schemas"]["LayerData"];
export type ShareUrl = components["schemas"]["ShareUrl"];
export type LinkData = components["schemas"]["LinkData"];
export type MarkerDataWithoutId = components["schemas"]["MarkerData"];
export type MarkerData = MarkerDataWithoutId & { id: string };
export type RouteDataWithoutState = components["schemas"]["RouteData"];
export type RouteData = Omit<RouteDataWithoutState, "markers"> & { state: RouteEditStateType, markers: MarkerData[] };
export type RouteSegmentData = components["schemas"]["RouteSegmentData"];
export type RoutingType = components["schemas"]["RouteSegmentData"]["routingType"];
export type DataContainer = components["schemas"]["DataContainer"];
export type UserPermissions = components["schemas"]["UserPermissions"];
export type ActivityType = ShareUrl["type"];

export type RouteEditStateType = "Poi" | "Route" | "ReadOnly" | "Hidden";
export type { Bounds } from "./bounds";
export type { EditableLayer } from "./editable-layer.js";
export type { Trace, TraceVisibility } from "./trace";
export type { OsmUserDetails } from "./osm-user-details";
export type { UserInfo } from "./user-info";
export type { SearchResultsPointOfInterest, EditablePublicPointData, UpdateablePublicPointData as UpdateablePublicPoiData } from "./point-of-interest";
export type { NorthEast } from "./north-east";
export type { CategoriesGroup, Category, IconColorLabel, CategoriesGroupType } from "./categories-group";
export type { Language, LanguageCode } from "./language";
export type { RecordedRoute } from "./recorded-route";
// states:
export type { ApplicationState, MutableApplicationState } from "./state/application-state";
export type { ConfigurationState, BatteryOptimizationType } from "./state/configuration-state";
export type { TracesState } from "./state/traces-state";
export type { LayersState } from "./state/layers-state";
export type { ShareUrlsState } from "./state/share-urls-state";
export type { UserState } from "./state/user-state";
export type { PointsOfInterestState } from "./state/poi-state";
export type { InMemoryState } from "./state/in-memory-state";
export type { OfflineState, TileMetadataPerFile, FileNameDateVersion } from "./state/offline-state";
export type { GpsState, TrackingStateType } from "./state/gps-state";
export type { RouteEditingState } from "./state/route-editing-state";
export type { RecordedRouteState } from "./state/recorded-route-state";
export type { StateWithHistory } from "./state/state-with-history";
export type { PaywallState } from "./state/paywall-state";
export type { LocationState } from "./state/location-state";
