# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the iOS app only"
  lane :build_ios do
    setup_ci

    sync_code_signing(type: "appstore")
    build_app(workspace: "App.xcworkspace", scheme: "App")
  end
  desc "Upload the previously built IPA to TestFlight"
  lane :upload_ios do
    upload_to_testflight(
      ipa: "build/App.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
