// <auto-generated />
using IsraelHiking.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IsraelHiking.DataAccess.Migrations
{
    [DbContext(typeof(IsraelHikingDbContext))]
    partial class IsraelHikingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("IsraelHiking.Common.SiteUrl", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("JsonData");

                    b.Property<DateTime>("LastViewed");

                    b.Property<string>("OsmUserId");

                    b.Property<string>("Title");

                    b.Property<int>("ViewsCount");

                    b.HasKey("Id");

                    b.ToTable("SiteUrls");
                });

            modelBuilder.Entity("IsraelHiking.Common.UserLayerData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<bool>("IsOverlay");

                    b.Property<string>("Key");

                    b.Property<int?>("MaxZoom");

                    b.Property<int?>("MinZoom");

                    b.Property<long>("UserLayersId");

                    b.HasKey("Id");

                    b.HasIndex("UserLayersId");

                    b.ToTable("UserLayerData");
                });

            modelBuilder.Entity("IsraelHiking.Common.UserLayers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OsmUserId");

                    b.HasKey("Id");

                    b.ToTable("UsersLayers");
                });

            modelBuilder.Entity("IsraelHiking.Common.UserLayerData", b =>
                {
                    b.HasOne("IsraelHiking.Common.UserLayers")
                        .WithMany("Layers")
                        .HasForeignKey("UserLayersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
